Fix #93, fix #94. Add front end section and fix up multiplayer section
audio-engineer/aau-p2-article pull request #102
Opened 2024-05-16 23:08 UTC by Danar435

2024-05-17 09:04 UTC, SebastianMygind requested changes
looks good except two minor issues.
Sorry for being pedantic, but i think it goes a long way for the overall quality of the article.

2024-05-17 09:04 UTC, SebastianMygind commented on src/problem-solution/frontend.tex
> +It'll go over every aspect of the website, from the landing page to the game interface, with explanations on how to
Generally never use abbreviations in "serious" literature

2024-05-17 09:04 UTC, SebastianMygind commented on src/problem-solution/frontend.tex
> +This will create add a new entry to the lobby, as seen in Figure~\ref{fig:lobby-game}.
create or add not both

2024-05-17 12:12 UTC, MadsHeilmann requested changes
I think the pictures included in the report should be in light mode, as that just looks nicer on the paper IMO. 

I also think that the front-end section reads to much like "redegørelse" or like a guide. Maybe i am wrong, but should it not have more analysis of why different design choises were made and how they enable learning and so on?

It is also to be considered to only include pictures, wherein there is no reference to the emulator, as that is not part of the product - only the development environment.

2024-05-17 12:12 UTC, MadsHeilmann commented on src/problem-analysis/multiplayer.tex
> +multiplayer has an effect on learning chess.
Maybe mention that it has a "positive" effect to be more clear

2024-05-17 12:12 UTC, MadsHeilmann commented on src/problem-analysis/multiplayer.tex
> +This can have a negative effect of the experience players have when learning and playing chess.
Is is not the opposite we are arguing? This sentence reads as if going from local to online is bad for learning. That may be true, but maybe then include a new sentence below saying something like "However, in the following section the benefits....". Right now it is like a "bad" cliffhanger before the next section which argues the opposite.

2024-05-17 13:11 UTC, Danar435 commented on src/problem-analysis/multiplayer.tex
> +This can have a negative effect of the experience players have when learning and playing chess.
You're right. The next section explains how online games have both upsides and downsides, so I think that a neutral stance is more correct.

2024-05-17 13:11 UTC, Danar435 commented on src/problem-analysis/multiplayer.tex
> +multiplayer has an effect on learning chess.
Refrence my other comment.

2024-05-17 21:11 UTC, SebastianMygind commented
IMPORTANT:

I have messed with some commits so Mads got some of his commit deleted, so it would probably be best to wait with adding more until it is fixed. AKA please don't merge before we fix the conflicts/deletions.

2024-05-18 11:00 UTC, Danar435 commented
I've added arguments behind some of the design choices and switched the images to light mode. I'm not sure if they look better, because the background blends in with the paper, but I can revert back if you're against it.

2024-05-18 11:11 UTC, audio-engineer approved these changes

2024-05-18 11:59 UTC, MadsHeilmann commented
You can maybe add a border around the images? I think that will look better.

2024-05-18 18:05 UTC, SebastianMygind submitted a review, later dismissed

2024-05-18 19:16 UTC, audio-engineer submitted a review, later dismissed

2024-05-18 19:17 UTC, audio-engineer approved these changes

2024-05-18 19:23 UTC, MadsHeilmann approved these changes

2024-05-18 19:23 UTC, merged