fix #85. Add first iteration of Conclusion
audio-engineer/aau-p2-article pull request #108
Opened 2024-05-18 20:03 UTC by SebastianMygind

I am not home tomorrow. So if you have anything you want to change please feel free to do so, as i think we need to have a conclusion when we send it to Andres.
You can also just merge it when it is ready as i am not home before late Sunday.

2024-05-18 20:04 UTC, audio-engineer approved these changes, later dismissed

2024-05-18 20:13 UTC, audio-engineer approved these changes, later dismissed

2024-05-18 21:27 UTC, MadsHeilmann requested changes

2024-05-18 21:27 UTC, MadsHeilmann commented on src/conclusion/conclusion.tex
> +strategies and new inventions.
Sentence reads weirdly

2024-05-18 21:27 UTC, MadsHeilmann commented on src/conclusion/conclusion.tex
> +make chess an unsolved game.
"test" in singular. New sentence after "time".

2024-05-18 21:27 UTC, MadsHeilmann commented on src/conclusion/conclusion.tex
> +The latest step in chess has been computer chess engines which reached beyond human skill with Deep Blue.
Replace "reached" with "reaches"

2024-05-18 21:27 UTC, MadsHeilmann commented on src/conclusion/conclusion.tex
> +Engines are now widely used for analysis, but the authors of this paper, have found that they also have immense
Second comma makes the senctence read weirdly. Consider removing it.

2024-05-18 21:27 UTC, MadsHeilmann commented on src/conclusion/conclusion.tex
> +The saying ``Once a student, now the master'' shows that learning from masters of their craft is nothing new, but
I dont think this has been mentioned in the report, why we either have to delete it from the conclusion or include it somewhere in the report.

2024-05-18 21:27 UTC, MadsHeilmann commented on src/conclusion/conclusion.tex
> +where engines can be the answer.
This sentence is good it just reads a little weird IMO.

2024-05-18 21:27 UTC, MadsHeilmann commented on src/conclusion/conclusion.tex
> +one could want
Missing a period and read a bit weird IMO

2024-05-18 21:27 UTC, MadsHeilmann commented on src/conclusion/conclusion.tex
> +ChessTeacher, does not cater to the completely novice players.
The start of this sentence makes no sense.

2024-05-18 21:27 UTC, MadsHeilmann commented on src/conclusion/conclusion.tex
> +The audience ChessTeacher will cater most to are beginners to intermediates, as they understand the rules and have begun
change "will cater" to "caters"

2024-05-18 21:27 UTC, MadsHeilmann commented on src/conclusion/conclusion.tex
> +learning patterns, which is also one aspect chess engines are superior to humans.
I dont think this belongs in the conclusion. It does not really make sense to conclude on who the users is IMO

2024-05-18 21:27 UTC, MadsHeilmann commented on src/conclusion/conclusion.tex
> +valid, as engines are the best chess players they should in theory also be the best teachers for chess, but this might
Maybe specify what ranking we are talking about.

2024-05-18 21:27 UTC, MadsHeilmann commented on src/conclusion/conclusion.tex
> +not be practical.
I dont think this point has been discussed yet, why we cant conclude on it. Maybe add an issue for it or write about it in the discussion section

2024-05-18 21:27 UTC, MadsHeilmann commented on src/conclusion/conclusion.tex
> +ChessTeacher.
I dont think we should say overlooked, as we are well aware of the short commings. Maybe change the wording

2024-05-18 21:27 UTC, MadsHeilmann commented on src/conclusion/conclusion.tex
> +context to why this move is good.
I dont think we should be speaking directly to the reader. Consider changing the "you" to "users"

2024-05-18 21:27 UTC, MadsHeilmann commented on src/conclusion/conclusion.tex
> +actual move the engines suggest.
Maybe change to "... just as critical for the learning of the users as the ..." to make sure focus is on learning

2024-05-18 21:27 UTC, MadsHeilmann commented on src/conclusion/conclusion.tex
> +technology seems perfect for this part, and they are Large-Language-Models (LLMs).
No need for suspense in the sentence. Consider removing the suspence

2024-05-18 21:40 UTC, SebastianMygind commented
@MadsHeilmann 
Valid feedback, but i do not have the time to change it before we need to send it to Andres, you can go onto my branch and do it, but i can't before we need to send it.

2024-05-18 22:32 UTC, MadsHeilmann commented
> @MadsHeilmann Valid feedback, but i do not have the time to change it before we need to send it to Andres, you can go onto my branch and do it, but i can't before we need to send it.

All good. Will do :)

2024-05-19 11:50 UTC, MadsHeilmann approved these changes, later dismissed

2024-05-19 20:46 UTC, Danar435 approved these changes, later dismissed

2024-05-19 22:16 UTC, Danar435 approved these changes

2024-05-19 22:17 UTC, SebastianMygind commented
This commit simply cleans the history and fixes merge problems. Still keeping @MadsHeilmann's changes

2024-05-20 08:01 UTC, MadsHeilmann approved these changes

2024-05-20 08:06 UTC, merged