Partially resolve #10. Add a section about multiplayer
audio-engineer/aau-p2-article pull request #22
Opened 2024-03-02 18:19 UTC by Danar435

2024-03-02 18:22 UTC, audio-engineer requested changes

2024-03-02 18:22 UTC, audio-engineer commented on src/problem-analysis/problem-analysis.tex
Missing final newline

2024-03-02 18:28 UTC, audio-engineer commented
Missing issue references in commits. You can manually move the issues now but next time use autoreference

2024-03-02 18:28 UTC, audio-engineer approved these changes

2024-03-02 23:28 UTC, Danar435 commented
I was hoping that naming the issue in the PR would associate it, oh well. But it works in my favor, as this PR only partially fixed the issue, it'll be fully fixed when @MadsHeilmann adds his section

2024-03-03 11:54 UTC, SebastianMygind approved these changes
nice

2024-03-03 13:10 UTC, merged